#!/usr/bin/env bash
# DO NOT EDIT — this file is generated from cm.yaml and will be overwritten.
# To make changes, edit cm.yaml and run: cm update
# Generated by container-magic: https://github.com/markhedleyjones/container-magic

set -euo pipefail

IMAGE_NAME="anomalica-ingester-pdf"
TAG="latest"
WORKDIR="/home/nonroot"
WORKSPACE_NAME="workspace"
SHELL="/bin/bash"

# Detect runtime backend
if command -v docker >/dev/null 2>&1; then
	RUNTIME="docker"
elif command -v podman >/dev/null 2>&1; then
	RUNTIME="podman"
else
	echo "Error: Neither docker nor podman found in PATH"
	exit 1
fi

# Check if image exists locally to avoid registry prompts
if ! ${RUNTIME} image inspect "${IMAGE_NAME}:${TAG}" &>/dev/null; then
	echo "Error: Image ${IMAGE_NAME}:${TAG} not found locally"
	echo "Build it with: ./build.sh"
	exit 1
fi

# Handle --stop (stop named container and exit)
if [[ "${1:-}" == "--stop" ]]; then
	${RUNTIME} stop "${IMAGE_NAME}" 2>/dev/null || true
	exit 0
fi

# Parse --detach/-d flag (first argument only)
DETACH=false
if [[ "${1:-}" == "--detach" ]] || [[ "${1:-}" == "-d" ]]; then
	DETACH=true
	shift
fi

# Parse runtime passthrough args (everything before --)
# Usage: ./run.sh -e DEBUG=1 -v /tmp:/data -- command args
RUNTIME_PASSTHROUGH=()
_PT_CMD_ARGS=()
_PT_FOUND_SEP=false
for arg in "$@"; do
	if [[ "${_PT_FOUND_SEP}" == false ]] && [[ "$arg" == "--" ]]; then
		_PT_FOUND_SEP=true
		continue
	fi
	if [[ "${_PT_FOUND_SEP}" == true ]]; then
		_PT_CMD_ARGS+=("$arg")
	else
		RUNTIME_PASSTHROUGH+=("$arg")
	fi
done
if [[ "${_PT_FOUND_SEP}" == true ]]; then
	set -- "${_PT_CMD_ARGS[@]}"
else
	RUNTIME_PASSTHROUGH=()
fi

# Build base run arguments (common to all commands)
BASE_RUN_ARGS=("--rm")
BASE_RUN_ARGS+=("--hostname" "${IMAGE_NAME}")
BASE_RUN_ARGS+=("--name" "${IMAGE_NAME}")
if [[ "${RUNTIME}" == "podman" ]]; then
	BASE_RUN_ARGS+=("--replace")
fi

# Additional bind mounts
BASE_RUN_ARGS+=("-v" "$HOME/.local/bin/claude:/usr/local/bin/claude:ro")
BASE_RUN_ARGS+=("-v" "$HOME/.claude:/home/nonroot/.claude")

# Load .env file if present
if [[ -f "$(pwd)/.env" ]]; then
	BASE_RUN_ARGS+=("--env-file" "$(pwd)/.env")
fi

# Runtime passthrough args
if [[ ${#RUNTIME_PASSTHROUGH[@]} -gt 0 ]]; then
	BASE_RUN_ARGS+=("${RUNTIME_PASSTHROUGH[@]}")
fi

# Use base run arguments
RUN_ARGS=("${BASE_RUN_ARGS[@]}")

if [[ "${DETACH}" == true ]]; then
	RUN_ARGS+=("--detach")
	if [ $# -gt 0 ]; then
		# Exec form: pass arguments directly (no shell wrapping).
		# Users who need shell features use: ./run.sh bash -c "cmd1 && cmd2"
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"$@"
	else
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"${SHELL}"
	fi
else
	if [ $# -gt 0 ]; then
		# Exec form: pass arguments directly (no shell wrapping)
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"$@"
	else
		# Interactive shell (add TTY flags only if stdin is a TTY)
		if [[ -t 0 ]]; then
			RUN_ARGS+=("--interactive" "--tty")
		fi
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"${SHELL}"
	fi
fi
