#!/usr/bin/env bash
# DO NOT EDIT — this file is generated from cm.yaml and will be overwritten.
# To make changes, edit cm.yaml and run: cm update
# Generated by container-magic: https://github.com/markhedleyjones/container-magic

set -euo pipefail

IMAGE_NAME="anomalica-ingester-pdf"
TAG="latest"
WORKDIR="/home/nonroot"
WORKSPACE_NAME="workspace"
SHELL="/bin/bash"

# Detect runtime backend
if command -v docker >/dev/null 2>&1; then
	RUNTIME="docker"
elif command -v podman >/dev/null 2>&1; then
	RUNTIME="podman"
else
	echo "Error: Neither docker nor podman found in PATH"
	exit 1
fi

# Check if image exists locally to avoid registry prompts
if ! ${RUNTIME} image inspect "${IMAGE_NAME}:${TAG}" &>/dev/null; then
	echo "Error: Image ${IMAGE_NAME}:${TAG} not found locally"
	echo "Build it with: ./build.sh"
	exit 1
fi

# Handle --stop (stop named container and exit)
if [[ "${1:-}" == "--stop" ]]; then
	${RUNTIME} stop "${IMAGE_NAME}" 2>/dev/null || true
	exit 0
fi

# Parse --detach/-d flag (first argument only)
DETACH=false
if [[ "${1:-}" == "--detach" ]] || [[ "${1:-}" == "-d" ]]; then
	DETACH=true
	shift
fi

# Parse runtime passthrough args (everything before --)
# Usage: ./run.sh -e DEBUG=1 -v /tmp:/data -- command args
RUNTIME_PASSTHROUGH=()
_PT_CMD_ARGS=()
_PT_FOUND_SEP=false
for arg in "$@"; do
	if [[ "${_PT_FOUND_SEP}" == false ]] && [[ "$arg" == "--" ]]; then
		_PT_FOUND_SEP=true
		continue
	fi
	if [[ "${_PT_FOUND_SEP}" == true ]]; then
		_PT_CMD_ARGS+=("$arg")
	else
		RUNTIME_PASSTHROUGH+=("$arg")
	fi
done
if [[ "${_PT_FOUND_SEP}" == true ]]; then
	set -- "${_PT_CMD_ARGS[@]}"
else
	RUNTIME_PASSTHROUGH=()
fi

# Build base run arguments (common to all commands)
BASE_RUN_ARGS=("--rm")
BASE_RUN_ARGS+=("--hostname" "${IMAGE_NAME}")
BASE_RUN_ARGS+=("--name" "${IMAGE_NAME}")
if [[ "${RUNTIME}" == "podman" ]]; then
	BASE_RUN_ARGS+=("--replace")
fi

# Additional bind mounts
BASE_RUN_ARGS+=("-v" "$HOME/.local/bin/claude:/usr/local/bin/claude:ro,z")
BASE_RUN_ARGS+=("-v" "$HOME/.claude:/home/nonroot/.claude:z")

# Load .env files (walk parent directories, most distant first so closer values win)
_env_files=()
_search_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while true; do
	if [[ -f "${_search_dir}/.env" ]]; then
		_env_files=("${_search_dir}/.env" "${_env_files[@]}")
	fi
	_parent="$(dirname "${_search_dir}")"
	if [[ "${_parent}" == "${_search_dir}" ]]; then
		break
	fi
	_search_dir="${_parent}"
done
for _env_file in "${_env_files[@]}"; do
	BASE_RUN_ARGS+=("--env-file" "${_env_file}")
done

# Runtime passthrough args
if [[ ${#RUNTIME_PASSTHROUGH[@]} -gt 0 ]]; then
	BASE_RUN_ARGS+=("${RUNTIME_PASSTHROUGH[@]}")
fi

# Custom command handlers

run_ingest() {
	# Extract structured content from a PDF
	local RUN_ARGS=("${BASE_RUN_ARGS[@]}")
	local CMD="python workspace/ingest_pdf.py"
	local EXTRA_ARGS=()
	# Environment variables
	RUN_ARGS+=("-e" "PYTHONUNBUFFERED=1")
	RUN_ARGS+=("-e" "PYTHONPATH=workspace")

	# Parse mount arguments
	local MANIFEST_LINES=()
	local REMAINING=()
	for arg in "$@"; do
		case "$arg" in
		input=*)
			local _host_path="${arg#input=}"
			local _resolved
			_resolved=$(realpath "$_host_path")
			if [[ ! -e "$_resolved" ]]; then
				echo "Error: Mount 'input' not found: $_host_path" >&2
				return 1
			fi
			local _basename
			_basename=$(basename "$_resolved")
			RUN_ARGS+=("-v" "${_resolved}:/mnt/input/${_basename}:ro,z")
			MANIFEST_LINES+=("${_resolved}:/mnt/input/${_basename}")
			;;
		output=*)
			local _host_path="${arg#output=}"
			local _resolved
			_resolved=$(realpath "$_host_path")
			mkdir -p "$_resolved"
			RUN_ARGS+=("-v" "${_resolved}:/mnt/output:z")
			MANIFEST_LINES+=("${_resolved}:/mnt/output")
			;;
		*)
			REMAINING+=("$arg")
			;;
		esac
	done
	local _manifest=""
	if [[ ${#MANIFEST_LINES[@]} -gt 0 ]]; then
		_manifest=$(mktemp /tmp/cm-manifest-XXXXXX)
		printf '%s\n' "${MANIFEST_LINES[@]}" >"$_manifest"
		RUN_ARGS+=("-v" "${_manifest}:/run/cm/mounts:ro,z")
	fi
	if [[ ${#REMAINING[@]} -gt 0 ]]; then
		EXTRA_ARGS+=("${REMAINING[@]}")
	fi
	if [[ ${#EXTRA_ARGS[@]} -gt 0 ]]; then
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}" \
			"${IMAGE_NAME}:${TAG}" \
			"${SHELL}" -c "${CMD} $(printf '%q ' "${EXTRA_ARGS[@]}")"
	else
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}" \
			"${IMAGE_NAME}:${TAG}" \
			"${SHELL}" -c "${CMD}"
	fi
	if [[ -n "$_manifest" ]]; then
		rm -f "$_manifest"
	fi
}

# Check for custom command
if [ $# -gt 0 ]; then
	case "$1" in
	ingest)
		shift
		run_ingest "$@"
		exit $?
		;;
	esac
fi

# Use base run arguments
RUN_ARGS=("${BASE_RUN_ARGS[@]}")

if [[ "${DETACH}" == true ]]; then
	RUN_ARGS+=("--detach")
	if [ $# -gt 0 ]; then
		# Exec form: pass arguments directly (no shell wrapping).
		# Users who need shell features use: ./run.sh bash -c "cmd1 && cmd2"
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"$@"
	else
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"${SHELL}"
	fi
else
	if [ $# -gt 0 ]; then
		# Exec form: pass arguments directly (no shell wrapping)
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"$@"
	else
		# Interactive shell (add TTY flags only if stdin is a TTY)
		if [[ -t 0 ]]; then
			RUN_ARGS+=("--interactive" "--tty")
		fi
		${RUNTIME} run "${RUN_ARGS[@]}" \
			-w "${WORKDIR}/${WORKSPACE_NAME}" \
			"${IMAGE_NAME}:${TAG}" \
			"${SHELL}"
	fi
fi
